[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'nodejs_20']

[phases.install]
cmds = [
    'composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader'
]

[phases.build]
cmds = [
    'npm ci',
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'php artisan backpack:publish-assets',
    'php artisan storage:link'
]

[start]
cmd = 'php artisan storage:link && php -S 0.0.0.0:${PORT:-8000} -t public/'
